### ISSUE TITLE
URL download support

### ISSUE THREAD

**Issue by jdoss** [asciinema/agg#1]
First off thank you so much for this! I am looking to add some animated demos to a presentation that I am giving this week and this will work super well!

It would be super cool if you could point `agg` at a URL such as https://asciinema.org/a/123456 and have it convert it without having to manually download the .cast file. This would let you save your recordings to asciinema.org and then convert them to a gif locally with ease.

**Comment by sickill** [comment]
Thanks! I'm glad you like it.

Support for URL download is coming, in ... 3 ... 2 ... 1 ...

**Comment by sickill** [comment]
I'll release this as 1.1.0 once figure out Github Actions build problem with OpenSSL.

**Comment by sickill** [comment]
It's out: https://github.com/asciinema/agg/releases/tag/v1.1.0

**Comment by jdoss** [comment]
Wonderful! Thank you for all of your awesome work!
