### ISSUE TITLE
Homebrew installation note

### ISSUE THREAD

**Issue by LangLangBart** [asciinema/agg#14]
Hello,

---

First of all thanks for creating this tool, especially the new `--font-dir` and `--font-family` flags are a welcome improvement compared to `asciicast2gif`. This allows the creation of GIFs with [nerdfont icons](https://www.nerdfonts.com/cheat-sheet).

---

Would you consider adding an installation note to your README for macOS users via Homebrew. Formula was added on [30/Aug/22](https://github.com/Homebrew/homebrew-core/pull/109174).

Shall I do a PR ?

PS: ...and maybe consider adding the [bump-homebrew-formula-action](https://github.com/mislav/bump-homebrew-formula-action) workflow to your `release.yml`.

**Comment by sickill** [comment]
Hey :wave: Thanks for your feedback. I'm glad you like `agg` and its new capabilities.

Regarding Homebrew, and packaging in general, I'd prefer to let others deal with that and stick to providing easy to follow build instructions (+ prebuilt binaries in GH releases for convenience). Thx for the suggestion anyway!
