### ISSUE TITLE
Character corruption with starship (Vagrant symbol)

### ISSUE THREAD

**Issue by shoffmeister** [asciinema/agg#19]
With a (very much default) starship (https://starship.rs/ - from `cargo install starship`) installation, the prompt contains a Vagrant symbol in the KDE `konsole` output proper.

The `agg` rendition of a screen cast does not show the Vagrant symbol, but a plain rectangle - see the very very right of the prompt.

`konsole` is configured to use `Cascadia Console PL 10pt` (https://github.com/microsoft/cascadia-code) and shows
![image](https://user-images.githubusercontent.com/3868036/192234280-09ae32f2-f6cd-4dbc-aca7-f4c1fa9c6bbe.png)

My emoji fonts are `google-noto-emoji-color-fonts.noarch`, `google-noto-emoji-fonts.noarch`.

All fonts are system fonts, as managed by Fedora Linux 36 (dnf install ...).

`asciinema` recording:  [starship.cast.zip](https://github.com/asciinema/agg/files/9644636/starship.cast.zip)

`agg` (43977bf11493650e76de0c9d4267bf0b4533255b) generates ![image](https://user-images.githubusercontent.com/3868036/192234872-a2e9b310-4473-4695-bb0c-6ddd39e83748.png) from `agg starship.cast starship.cast.gif`

I believe I got the font configuration consistent and correct, on the system, in `konsole`, and for `agg`

**Comment by shoffmeister** [comment]
This might be https://github.com/RazrFalcon/fontdb/pull/26

**Comment by sickill** [comment]
I've just released 1.4.0 with much improved font loading and rendering behaviour. Please give it a try. Also see new [Fonts](https://github.com/asciinema/agg#fonts) section in README.
