### ISSUE TITLE
Terminal emoji not appearing on macOS

### ISSUE THREAD

**Issue by woodruffw** [asciinema/agg#20]
First of all, thanks for making this tool! I'm really glad to see a modern replacement to `asciicast2gif`, and using it has been incredibly easy!

This is a partial dupe of #2, except on macOS instead of Linux.

When I try to render [this asciicast](https://asciinema.org/a/524144) with a build of the latest `main` and the font workaround in #2:

```
./target/release/agg 524144.cast abi3audit.gif --font-dir=~/Downloads/Noto_Emoji/static/
```

I get frames that are still missing emoji:

<img width="589" alt="Screen Shot 2022-09-27 at 7 04 47 PM" src="https://user-images.githubusercontent.com/3059210/192652830-5d1af1a5-575a-4457-9572-ba372fc83059.png">

whereas my expected output is something like that on the asciinema website, but with B&W emoji instead:

<img width="944" alt="Screen Shot 2022-09-27 at 7 05 24 PM" src="https://user-images.githubusercontent.com/3059210/192652888-ddcdf2b8-6c18-4220-8ff0-6656b4aff0cc.png">

I downloaded the Noto Emoji fonts from the same Google Fonts source as in #2, and I can confirm that they're actually present at that directory:

```console
$ ls ~/Downloads/Noto_Emoji/static/
NotoEmoji-Bold.ttf	NotoEmoji-Regular.ttf
NotoEmoji-Light.ttf	NotoEmoji-SemiBold.ttf
NotoEmoji-Medium.ttf
```

Please let me know if there's any additional information I can provide, and thank you in advance!

**Comment by zachriggle** [comment]
I'm having this issue as well, but not with emoji, but rather SF Symbols.

https://developer.apple.com/sf-symbols/

**Comment by curio-sitas** [comment]
I have the same problem with emojis and tried with `Noto Emojis` and `Noto Color Emojis` and other fonts that i use.

Produced with `asciinema` online : 
[![asciicast](https://asciinema.org/a/3d6WVpcr8MESiN32yOJ7DXASK.svg)](https://asciinema.org/a/3d6WVpcr8MESiN32yOJ7DXASK)

Produced with `agg` : 
![test](https://user-images.githubusercontent.com/26415466/197395099-53fc69d8-1079-4119-a30b-2e17467d5172.gif)

**Comment by sickill** [comment]
I've just released 1.4.0 with much improved font loading and rendering behaviour. Please give it a try. 

The emojis should now be rendered in monochrome as long as you install Noto Emoji font - see new [Fonts](https://github.com/asciinema/agg#fonts) section in README.

There's still issue of double-column characters (like most emojis) not being aligned properly, but that's a deeper issue which we'll tack separately.

![issue-20](https://user-images.githubusercontent.com/17589/228838655-736febc8-0565-4e71-99fc-38d2454bd458.gif)

**Comment by woodruffw** [comment]
Thanks @sickill, that's fantastic! I'll have a chance to give it a spin soon 🙂 

(And thanks again a ton for creating and maintaining Asciinema!)

**Comment by sickill** [comment]
Assuming v1.4 solved the issue. Ping me if otherwise, I'll re-open in that case.

**Comment by ku1ik** [comment]
Hi! A quick follow-up here: agg 1.8.0 is out and includes explicit support for Apple Color Emoji on macOS, plus a new default text rendering backend and improved emoji font fallback.

This issue is old and was already closed, but if you still use agg on macOS, the emoji behavior should be much better now without extra font setup.

<img width="852" height="588" alt="Image" src="https://github.com/user-attachments/assets/9253c839-5b4e-47c5-9c77-e563d9dcd5a7" />
