### ISSUE TITLE
Weird Chinese rendering

### ISSUE THREAD

**Issue by liblaf** [asciinema/agg#25]
When I use Chinese in terminal it looks fine like this

![image](https://user-images.githubusercontent.com/30631553/201460521-083cf597-0359-4315-bae4-f923bad458b4.png)

But when I render it as a gif using agg , the Chinese becomes weird

```sh
agg --renderer resvg --font-dir "${HOME}/.local/share/fonts/MesloLGS NF" --font-family "MesloLGS NF" demo.cast demo.gif
```

![demo](https://user-images.githubusercontent.com/30631553/201460590-c2f68d08-278f-424e-b5ab-a98c20f6f5ad.gif)

If I use `fontdb` as renderer, then Chinese will not be displayed.

**Comment by a2659802** [comment]
see also https://github.com/asciinema/agg/issues/10

**Comment by dlf412** [comment]
you can edit cast file: add a space character  as placeholder after all chinese characters

**Comment by zetako** [comment]
> you can edit cast file: add a space character as placeholder after all chinese characters

This works well! Thanks! I'm using a perl command to convert it now.

(It should be a sed cmd for general usage, but I'm having trouble making sed support unicode)

```shell
cat demo.cast | perl -CS -pe 's/([\x{4e00}-\x{9fa5}]|[\x{3040}-\x{30ff}])/$1 /g' > demo.space.cast
```

The first part (\u4e00-\u9fa5) matches basic CJKs and second part (\u3040-\u30ff) matches japanese kanas. These seems enough for me, check [wiki](https://w.wiki/6$MX) if u need other blocks.

**Comment by hustcer** [comment]
@zetako Works for me, thanks

**Comment by ku1ik** [comment]
I believe this is the same problem as in #10 so I'm closing this as duplicate.
