### ISSUE TITLE
Default command errors with unhelpful error message: no faces matching font family

### ISSUE THREAD

**Issue by paololazzari** [asciinema/agg#26]
In ubuntu WSL:

```bash
$ agg /tmp/tmpwgt1f50h-ascii.cast demo.gif
Error: no faces matching font family JetBrains Mono,Fira Code,SF Mono,Menlo,Consolas,DejaVu Sans Mono,Liberation Mono
```

the recording was created with the default `asciinema rec` command

**Comment by Josh-zjx** [comment]
I just encountered the exact same problem and solved it by installing any one of these fonts it mentioned. I  am using manjaro on WSL2 so I just run 
`sudo pacman -S ttf-jetbrains-mono`
There should be similar solutions in Ubuntu.

**Comment by paololazzari** [comment]
Thank you @Josh-zjx 

This worked for me in ubuntu:

```bash
sudo apt-get install -y fonts-jetbrains-mono
```
