### ISSUE TITLE
thank you 🙏 for making this project. ability to convert asciicast or gif to video file format

### ISSUE THREAD

**Issue by ipatch** [asciinema/agg#4]
first off, thanks for spending the time to make this project. i'm sure i'll come back to it from time to time to make a gif that can be embedded into a github repo. that said github recently started supporting movie based file formats. the movie i believe has to be under 10MB or less. but would you have a recommendation for converting an asciicast to h264 video file format or converting the gif to a video file format?

thanks again for putting this together.

**Comment by sickill** [comment]
Thanks! I'm glad you like it.

Regarding conversion to video format - I'm not sure what would be the best tool these days, but I guess I'd start with using `agg` to create a gif file (but _not_ using `gifsicle` to not lose quality), then convert gif to h264 with `ffmpeg`.

**Comment by gerhard** [comment]
# +💯 thank you

`asciinema` + `agg` makes recording & sharing terminal sessions a breeze!
