### ISSUE TITLE
Fira Code Nerd Font doesn't render correctly

### ISSUE THREAD

**Issue by pieterdd** [asciinema/agg#44]
_(Sidenote: very pleased to discover this official tool from the asciinema team to render recordings to video. Small file sizes, no notable compression artifacts, written in Rust, good job guys!)_

**Describe the bug**
`agg` seems to have trouble rendering some Nerd Font characters that otherwise render normally for me. Here's a comparison of GIF render vs. web player:

![image](https://github.com/asciinema/agg/assets/1407980/d6e1fc59-83c7-4d0e-b558-0e9cce89b68e)

![image](https://github.com/asciinema/agg/assets/1407980/7f127d0d-8f8c-4274-b1f2-444595ee98dc)

**To Reproduce**
1. Set your terminal font to FiraCode Nerd Font Mono
2. Start a recording
3. Trigger the rendering of a character requiring a Nerd Font
4. Observe that the rendering works correctly locally
5. Finish the recording and upload it
6. On the asciinema.org page of your recording, observe that the character doesn't get rendered correctly
7. Set the 'Terminal font family' setting of your recording to 'Nerd Font - Fira Code' and save
8. Observe that the character rendering has been fixed on the website
9. Render the GIF

**Expected behavior**
The character should render correctly in the GIF as well.

**Versions:**
 - OS: Windows 11 running Ubuntu LTS in WSL 2
 - agg: 1.4.1

**Additional context**
I used the Windows Terminal app.

**Comment by sickill** [comment]
Hey Pieter, thanks for appreciation!

I assume you read this section https://github.com/asciinema/agg#fonts ?
What's the command line, and how are you specifying the font-family option?

**Comment by pieterdd** [comment]
Apologies, I had missed that part. When invoked as `agg --font-family "FiraCode Nerd Font Mono" testfoo.cast testfoo.gif`, this is what I see in the GIF:

![image](https://github.com/asciinema/agg/assets/1407980/a39d6ea6-a981-4389-afb4-ae98cbd01a4f)

This is what I see in reality while recording:

![image](https://github.com/asciinema/agg/assets/1407980/234c9641-0182-4916-b8ba-44814387c47a)

It's not pixel-perfect, but it does indeed work. I can imagine that these fonts are kinda tricky to work with so I'd be okay closing the thread.
