### ISSUE TITLE
Initial frame erroneously shows a bunch of later output

### ISSUE THREAD

**Issue by badeball** [asciinema/agg#45]
**Describe the bug**

The resulting Gif's initial frames contain a bunch of output which in reality takes much longer to actually be outputted.

**To Reproduce**

1. Download https://asciinema.org/a/Muvp1oofnYotCnXHTpDezCYtA
2. Use `agg` to render into a Gif: `agg 589983.cast 589983.gif`
3. Watch the Gif: while the ascii recording on the web correctly shows that the command takes a while to get started, this isn't reflected in the Gif

![589983](https://github.com/asciinema/agg/assets/730419/9ed79f2a-3fba-468f-b407-0bf742c2545a)

**Expected behavior**

For the recording as shown on the web and the rendered Gif to be somewhat similar.

**Versions:**
 - OS: Arch Linux
 - agg: 1.4.1

**Comment by sickill** [comment]
Good catch. I think we're using first print for the initial frame,  while we need initial frame to be blank.

**Comment by sickill** [comment]
Just released 1.4.2 with a fix for this.

**Comment by badeball** [comment]
Excellent, thanks! It works splendidly.
