### ISSUE TITLE
Installation via cargo results in error. It leads to "failed to parse manifest".

### ISSUE THREAD

**Issue by WilliamBonvini** [asciinema/agg#46]
**Describe the bug**
`cargo install --git https://github.com/asciinema/agg`

leads to 

```
error: failed to parse manifest at `/Users/chattershuts/.cargo/git/checkouts/agg-d92013fdd4380564/39223d5/Cargo.toml`

Caused by:
  feature `edition2021` is required

  this Cargo does not support nightly features, but if you
  switch to nightly channel you can add
  `cargo-features = ["edition2021"]` to enable this feature
 ```

**To Reproduce**
1. open terminal
2. run `cargo install --git https://github.com/asciinema/agg`
3. Get error

**Expected behavior**
I expect the command to successfully install agg

**Versions:**
 - OS: macOS 13.4 with M1
 - agg: 1.4.2

**Comment by sickill** [comment]
Do you have Rust 1.56 or newer?

**Comment by WilliamBonvini** [comment]
I have Rust 1.54.0. Should I upgrade to 1.56?

**Comment by sickill** [comment]
README states you need at least 1.56.

**Comment by WilliamBonvini** [comment]
thank you, sorry but I didn't notice that part when I first read it. Problem solved.

**Comment by sickill** [comment]
No worries. I'm glad you got it running.
