### ISSUE TITLE
Unable to `nix run`

### ISSUE THREAD

**Issue by srid** [asciinema/agg#48]
This seems to be because `naersk` is setting a wrong `meta.mainProgram` (ie., includes version string unnecessarily)

```
❯ nix run github:asciinema/agg
error: unable to execute '/nix/store/4vwhkp4c8vdxv3j0yr0llv5dc0h5r0jg-agg-1.4.2/bin/agg-1.4.2': No such file or directory
```

```
❯ ls /nix/store/4vwhkp4c8vdxv3j0yr0llv5dc0h5r0jg-agg-1.4.2/bin
agg
```

**Comment by srid** [comment]
Related: I use dream2nix to package Rust programs (`nix run` works well here): https://github.com/srid/rust-nix-template

**Comment by sickill** [comment]
What is naersk?

**Comment by srid** [comment]
[The nix builder used by this project](https://github.com/nix-community/naersk)

https://github.com/asciinema/agg/blob/20d965baa069d9ba04d62c3aaf3c4f8738b84582/flake.nix#L3

**Comment by sickill** [comment]
I see. I'm not familiar with this. @yvan-sraka can you help?
