### ISSUE TITLE
gif timecode length to asciicast time length seem different

### ISSUE THREAD

**Issue by ipatch** [asciinema/agg#5]
hello again 👋,

ran this cmd locally for the first this afternoon after creating the below cast.

https://asciinema.org/a/515723

i used the cmd supplied by the readme after creating the cast.

```
agg freecad.reset.repo.cast freecad.reset.repo.gif      
```

i used the below cmd to create cast,

```
 asciinema rec -i=2 ~/media/movies/my.recordings/asciicasts/freecad.ascii.recordings/freecad.reset.repo.cast  
 ```

i use the `-i=2` to hopefully only allow 2 seconds of "dead space", but i don't think this program `agg` is reading the cast file properly and is not processing the "strip out dead space" between movement.

below is the gif that is created from running the above cmd

<details>

<summary>gif 📽</summary>

![freecad reset repo](https://user-images.githubusercontent.com/613805/185458466-676b2384-9b96-47c1-80be-abce5a0fc3c1.gif)

</details>

after creating that gif there is significant delay between commands run in the cast.

and can be seen / verified by importing / opening the gif in a video editor such as shotcut

![image](https://user-images.githubusercontent.com/613805/185458838-87d9f14a-79f1-48d6-b99f-f7b0eab426eb.png)

looking at the above image / gif that was created with `agg` the length of the file / timecode is ~ 4 minutes and 11 seconds.

that same asciicast is only ~ 1 minute and 20 seconds.

**Comment by sickill** [comment]
Good catch. Recording with `-i=2` saves `idle_time_limit: 2.0` in asciicast file header (1st line). This field is honored by the web player as well as by `asciinema play ...` in terminal. That should be pretty straightforward to add here.

**Comment by sickill** [comment]
Meanwhile, if you want to strip the pauses you can do the following:

1. `asciinema rec -c "asciinema play demo.cast"  demo-no-pauses.cast` - this will re-record with pauses removed from the initial recording (`play` will strip them and `rec` will record it, as if the pauses were never there)
2. `agg demo-no-pauses.cast demo.gif`
