### ISSUE TITLE
Enhancement: Generated default output filename

### ISSUE THREAD

**Issue by aooohan** [asciinema/agg#52]
In most of my scenarios, I specify filename in advance when record terminal session, sometimes the name is very long, and it's a bit cumbersome and not very convenient to specify the output name frequently when converting. It will be convenient that generated a default output filename based on the input filename ; )

Is it possible ?

**Comment by ku1ik** [comment]
That's something that your shell can already do:

```bash
agg very-long-name-of-my-recording.{cast,gif}
```

Given you can do the above I don't see a need to implement this in agg itself.
