### ISSUE TITLE
Cannot find docker image

### ISSUE THREAD

**Issue by D3vil0p3r** [asciinema/agg#53]
Could you please fix the command for pulling the docker image of agg? It seems to not work.

**Comment by ku1ik** [comment]
I don't remember including a command for pulling the image anywhere. If you refer to the one in the README then it's for building the image from source code checkout.

What's the command you tried?

**Comment by D3vil0p3r** [comment]
Sorry, it was my misunderstanding... I needed to clone the repo and then build it... Is there the chance to upload the docker image to Docker Hub or similar?

**Comment by ku1ik** [comment]
I've moved other asciinema images from Docker Hub to Github's ghcr.io, so if we create one for agg then it will likely be on ghcr.io as well. In the future we could extend release workflow in GH Actions to create image for tagged commits, but at the moment I'm busy with other things so I can't give an ETA. Happy to accept a PR though.
