### ISSUE TITLE
agg doesn't seem to pick up on colors inside nvim

### ISSUE THREAD

**Issue by mxple** [asciinema/agg#74]
**Describe the bug**
agg doesn't pick on colors in neovim. agg works for vim, and `asciinema stream` also capture colors.

**Versions:**
 - OS: 6.9.6 Arch
asciinema: 3.0.0-rc.3
agg: 1.4.3

**Additional context**
gif output from `agg`
![example](https://github.com/asciinema/agg/assets/83033020/25f17053-67f2-4b1f-969c-a1c658e6f1dc)

screenshot of `asciinema stream`
![image](https://github.com/asciinema/agg/assets/83033020/f6bef7c2-11b4-4346-b10e-633874b185f8)

**Comment by ku1ik** [comment]
I think I know what's up. Do you happen to use Kitty or WezTerm as your terminal?

**Comment by mxple** [comment]
I use kitty

**Comment by baco** [comment]
and, what's the workaround, then?

**Comment by mxple** [comment]
> and, what's the workaround, then?

No longer using agg but try setting `TERM=xterm`. Many terminal programs do not recognize `xterm-kitty` and do not produce color escape codes for unknown terminals.

**Comment by ku1ik** [comment]
This should now be fixed in the `main` branch.

**Comment by baco** [comment]
You're right @ku1ik, it is solved in `main`.  Thank you very much!!!

I guess we just have to wait for the next release.

**Comment by ku1ik** [comment]
Great to hear. I'm planning a new release soon, likely within a couple of days.

**Comment by ku1ik** [comment]
agg 1.5.0 with the above fix is out: https://github.com/asciinema/agg/releases/tag/v1.5.0
